In [7]:

# ============================================================
# STEP 5: DEBUGGING DATE AND LEAD-TIME VALUES
# ============================================================

import pandas as pd
import numpy as np

# Use the original dataset if it is still available
try:
    raw_df = df.copy()
except NameError:
    raw_df = pd.read_csv("Nassau Candy Distributor.csv")

print("=" * 60)
print("1. ORIGINAL DATE VALUES")
print("=" * 60)

display(
    raw_df[["Order ID", "Order Date", "Ship Date"]].head(15)
)

print("\nOriginal date data types:")
print(raw_df[["Order Date", "Ship Date"]].dtypes)

print("\n" + "=" * 60)
print("2. DATE RANGES AFTER PARSING")
print("=" * 60)

for dayfirst in [False, True]:

    order_dates = pd.to_datetime(
        raw_df["Order Date"],
        errors="coerce",
        dayfirst=dayfirst
    )

    ship_dates = pd.to_datetime(
        raw_df["Ship Date"],
        errors="coerce",
        dayfirst=dayfirst
    )

    lead_time = (ship_dates - order_dates).dt.days

    valid = order_dates.notna() & ship_dates.notna()
    valid_lead = lead_time[valid]

    print("\nDay-first setting:", dayfirst)
    print("Earliest order:", order_dates.min())
    print("Latest order:", order_dates.max())
    print("Earliest ship:", ship_dates.min())
    print("Latest ship:", ship_dates.max())
    print("Invalid order dates:", order_dates.isna().sum())
    print("Invalid ship dates:", ship_dates.isna().sum())
    print("Negative lead times:", (valid_lead < 0).sum())

    if len(valid_lead) > 0:
        print("\nLead-time statistics:")
        print(valid_lead.describe())

print("\n" + "=" * 60)
print("3. ORDER ID YEAR CHECK")
print("=" * 60)

print(
    raw_df["Order ID"]
    .astype(str)
    .str.extract(r"US-(\d{4})")[0]
    .value_counts()
    .sort_index()
)

print("\n" + "=" * 60)
print("4. LARGEST LEAD TIMES")
print("=" * 60)

order_dates = pd.to_datetime(
    raw_df["Order Date"], errors="coerce"
)
ship_dates = pd.to_datetime(
    raw_df["Ship Date"], errors="coerce"
)

check_df = raw_df[
    ["Order ID", "Order Date", "Ship Date"]
].copy()

check_df["Parsed_Order_Date"] = order_dates
check_df["Parsed_Ship_Date"] = ship_dates
check_df["Lead_Time_Days"] = (
    ship_dates - order_dates
).dt.days

display(
    check_df.sort_values(
        "Lead_Time_Days", ascending=False
    ).head(15)
)

============================================================
1. ORIGINAL DATE VALUES
============================================================

                        Order ID  Order Date   Ship Date
0   US-2021-103800-CHO-MIL-31000  03-01-2024  30-06-2026
1   US-2021-112326-CHO-TRI-54000  04-01-2024  01-07-2026
2   US-2021-112326-CHO-NUT-13000  04-01-2024  01-07-2026
3   US-2021-112326-CHO-SCR-58000  04-01-2024  01-07-2026
4   US-2021-141817-CHO-TRI-54000  05-01-2024  05-07-2026
5   US-2021-167199-CHO-SCR-58000  06-01-2024  03-07-2026
6   US-2021-167199-CHO-TRI-54000  06-01-2024  03-07-2026
7   US-2021-106054-CHO-MIL-31000  06-01-2024  30-06-2026
8   US-2021-167199-CHO-NUT-13000  06-01-2024  03-07-2026
9   US-2021-167199-CHO-MIL-31000  06-01-2024  03-07-2026
10  US-2021-167199-CHO-MIL-31000  06-01-2024  03-07-2026
11  US-2021-130813-CHO-MIL-31000  06-01-2024  01-07-2026
12  US-2021-167199-CHO-SCR-58000  06-01-2024  03-07-2026
13  US-2021-167199-CHO-FUD-51000  06-01-2024  03-07-2026
14  US-2021-105417-CHO-MIL-31000  07-01-2024  05-07-2026

Original date data types:
Order Date    object
Ship Date     object
dtype: object

============================================================
2. DATE RANGES AFTER PARSING
============================================================

Day-first setting: False
Earliest order: 2024-01-02 00:00:00
Latest order: 2025-12-12 00:00:00
Earliest ship: 2026-06-30 00:00:00
Latest ship: 2030-06-28 00:00:00
Invalid order dates: 6064
Invalid ship dates: 0
Negative lead times: 0

Lead-time statistics:
count    4130.000000
mean     1366.009685
std       302.829972
min       613.000000
25%      1155.000000
50%      1361.000000
75%      1598.000000
max      1965.000000
dtype: float64

Day-first setting: True
Earliest order: 2024-01-02 00:00:00
Latest order: 2025-12-31 00:00:00
Earliest ship: 2026-06-30 00:00:00
Latest ship: 2030-06-28 00:00:00
Invalid order dates: 0
Invalid ship dates: 0
Negative lead times: 0

Lead-time statistics:
count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
dtype: float64

============================================================
3. ORDER ID YEAR CHECK
============================================================
0
2021    1993
2022    2102
2023    2587
2024    3312
Name: count, dtype: int64

============================================================
4. LARGEST LEAD TIMES
============================================================

C:\Users\AKARSH.K\AppData\Local\Temp\ipykernel_8724\3025809779.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ship_dates = pd.to_datetime(
C:\Users\AKARSH.K\AppData\Local\Temp\ipykernel_8724\3025809779.py:80: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ship_dates = pd.to_datetime(

,Order ID,Order Date,Ship Date,Parsed_Order_Date,Parsed_Ship_Date,Lead_Time_Days
9712,US-2024-166926-CHO-FUD-51000,01-12-2025,31-05-2030,2025-01-12,2030-05-31,1965.0
9731,US-2024-166926-CHO-MIL-31000,01-12-2025,31-05-2030,2025-01-12,2030-05-31,1965.0
9730,US-2024-138618-CHO-SCR-58000,01-12-2025,31-05-2030,2025-01-12,2030-05-31,1965.0
9724,US-2024-135860-CHO-SCR-58000,01-12-2025,30-05-2030,2025-01-12,2030-05-30,1964.0
9728,US-2024-135860-CHO-NUT-13000,01-12-2025,30-05-2030,2025-01-12,2030-05-30,1964.0
9743,US-2024-135860-CHO-SCR-58000,01-12-2025,30-05-2030,2025-01-12,2030-05-30,1964.0
9734,US-2024-135860-CHO-FUD-51000,01-12-2025,30-05-2030,2025-01-12,2030-05-30,1964.0
9718,US-2024-103968-CHO-TRI-54000,01-12-2025,30-05-2030,2025-01-12,2030-05-30,1964.0
9736,US-2024-135860-CHO-MIL-31000,01-12-2025,30-05-2030,2025-01-12,2030-05-30,1964.0
9737,US-2024-101805-CHO-FUD-51000,01-12-2025,29-05-2030,2025-01-12,2030-05-29,1963.0
9722,US-2024-101805-CHO-TRI-54000,01-12-2025,29-05-2030,2025-01-12,2030-05-29,1963.0
9713,US-2024-143245-CHO-NUT-13000,01-12-2025,29-05-2030,2025-01-12,2030-05-29,1963.0
9732,US-2024-143245-CHO-FUD-51000,01-12-2025,29-05-2030,2025-01-12,2030-05-29,1963.0
9716,US-2024-101805-CHO-NUT-13000,01-12-2025,29-05-2030,2025-01-12,2030-05-29,1963.0
9727,US-2024-144862-OTH-GUM-21000,01-12-2025,28-05-2030,2025-01-12,2030-05-28,1962.0

In [8]:

# ============================================================
# STEP 5: CORRECT DATE PARSING AND VALIDATION
# ============================================================

import pandas as pd
import numpy as np

# Reload original data to avoid using previously parsed dates
df_check = pd.read_csv("Nassau Candy Distributor.csv")

# Parse dates explicitly as day-month-year
df_check["Order Date"] = pd.to_datetime(
    df_check["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df_check["Ship Date"] = pd.to_datetime(
    df_check["Ship Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

# Calculate lead time
df_check["Lead_Time_Days"] = (
    df_check["Ship Date"] - df_check["Order Date"]
).dt.days

print("ORDER DATE RANGE")
print(df_check["Order Date"].min())
print(df_check["Order Date"].max())

print("\nSHIP DATE RANGE")
print(df_check["Ship Date"].min())
print(df_check["Ship Date"].max())

print("\nLEAD TIME SUMMARY")
print(df_check["Lead_Time_Days"].describe())

print("\nINVALID ORDER DATES:",
      df_check["Order Date"].isna().sum())

print("INVALID SHIP DATES:",
      df_check["Ship Date"].isna().sum())

print("NEGATIVE LEAD TIMES:",
      (df_check["Lead_Time_Days"] < 0).sum())

print("LEAD TIMES ABOVE 90 DAYS:",
      (df_check["Lead_Time_Days"] > 90).sum())

print("\nSAMPLE RECORDS WITH LEAD TIMES ABOVE 90 DAYS")

display(
    df_check.loc[
        df_check["Lead_Time_Days"] > 90,
        [
            "Order ID",
            "Order Date",
            "Ship Date",
            "Lead_Time_Days"
        ]
    ].head(15)
)

print("\nORDER ID YEAR COMPARISON")

df_check["Order_ID_Year"] = pd.to_numeric(
    df_check["Order ID"]
    .astype(str)
    .str.extract(r"US-(\d{4})")[0],
    errors="coerce"
)

df_check["Order_Date_Year"] = (
    df_check["Order Date"].dt.year
)

display(
    df_check[
        [
            "Order ID",
            "Order Date",
            "Order_ID_Year",
            "Order_Date_Year"
        ]
    ].head(15)
)

print("\nDATE VALIDATION CHECK COMPLETED")

ORDER DATE RANGE
2024-01-02 00:00:00
2025-12-31 00:00:00

SHIP DATE RANGE
2026-06-30 00:00:00
2030-06-28 00:00:00

LEAD TIME SUMMARY
count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead_Time_Days, dtype: float64

INVALID ORDER DATES: 0
INVALID SHIP DATES: 0
NEGATIVE LEAD TIMES: 0
LEAD TIMES ABOVE 90 DAYS: 10194

SAMPLE RECORDS WITH LEAD TIMES ABOVE 90 DAYS

                        Order ID Order Date  Ship Date  Lead_Time_Days
0   US-2021-103800-CHO-MIL-31000 2024-01-03 2026-06-30             909
1   US-2021-112326-CHO-TRI-54000 2024-01-04 2026-07-01             909
2   US-2021-112326-CHO-NUT-13000 2024-01-04 2026-07-01             909
3   US-2021-112326-CHO-SCR-58000 2024-01-04 2026-07-01             909
4   US-2021-141817-CHO-TRI-54000 2024-01-05 2026-07-05             912
5   US-2021-167199-CHO-SCR-58000 2024-01-06 2026-07-03             909
6   US-2021-167199-CHO-TRI-54000 2024-01-06 2026-07-03             909
7   US-2021-106054-CHO-MIL-31000 2024-01-06 2026-06-30             906
8   US-2021-167199-CHO-NUT-13000 2024-01-06 2026-07-03             909
9   US-2021-167199-CHO-MIL-31000 2024-01-06 2026-07-03             909
10  US-2021-167199-CHO-MIL-31000 2024-01-06 2026-07-03             909
11  US-2021-130813-CHO-MIL-31000 2024-01-06 2026-07-01             907
12  US-2021-167199-CHO-SCR-58000 2024-01-06 2026-07-03             909
13  US-2021-167199-CHO-FUD-51000 2024-01-06 2026-07-03             909
14  US-2021-105417-CHO-MIL-31000 2024-01-07 2026-07-05             910

ORDER ID YEAR COMPARISON

                        Order ID Order Date  Order_ID_Year  Order_Date_Year
0   US-2021-103800-CHO-MIL-31000 2024-01-03         2021.0             2024
1   US-2021-112326-CHO-TRI-54000 2024-01-04         2021.0             2024
2   US-2021-112326-CHO-NUT-13000 2024-01-04         2021.0             2024
3   US-2021-112326-CHO-SCR-58000 2024-01-04         2021.0             2024
4   US-2021-141817-CHO-TRI-54000 2024-01-05         2021.0             2024
5   US-2021-167199-CHO-SCR-58000 2024-01-06         2021.0             2024
6   US-2021-167199-CHO-TRI-54000 2024-01-06         2021.0             2024
7   US-2021-106054-CHO-MIL-31000 2024-01-06         2021.0             2024
8   US-2021-167199-CHO-NUT-13000 2024-01-06         2021.0             2024
9   US-2021-167199-CHO-MIL-31000 2024-01-06         2021.0             2024
10  US-2021-167199-CHO-MIL-31000 2024-01-06         2021.0             2024
11  US-2021-130813-CHO-MIL-31000 2024-01-06         2021.0             2024
12  US-2021-167199-CHO-SCR-58000 2024-01-06         2021.0             2024
13  US-2021-167199-CHO-FUD-51000 2024-01-06         2021.0             2024
14  US-2021-105417-CHO-MIL-31000 2024-01-07         2021.0             2024

DATE VALIDATION CHECK COMPLETED

In [9]:

# ============================================================
# INVESTIGATE THE SOURCE DATA DATE ISSUE
# ============================================================

import pandas as pd

check = pd.read_csv("Nassau Candy Distributor.csv")

# Parse dates using the confirmed format
check["Order_Date_Parsed"] = pd.to_datetime(
    check["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

check["Ship_Date_Parsed"] = pd.to_datetime(
    check["Ship Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

check["Lead_Time_Days"] = (
    check["Ship_Date_Parsed"]
    - check["Order_Date_Parsed"]
).dt.days

# Extract the year embedded in Order ID
check["Order_ID_Year"] = pd.to_numeric(
    check["Order ID"]
    .astype(str)
    .str.extract(r"US-(\d{4})")[0],
    errors="coerce"
)

# 1. Compare years
print("ORDER ID YEAR COUNTS")
print(check["Order_ID_Year"].value_counts().sort_index())

print("\nORDER DATE YEAR COUNTS")
print(check["Order_Date_Parsed"].dt.year.value_counts().sort_index())

print("\nSHIP DATE YEAR COUNTS")
print(check["Ship_Date_Parsed"].dt.year.value_counts().sort_index())

# 2. Compare order ID year with order date year
check["Order_Year_Mismatch"] = (
    check["Order_ID_Year"]
    != check["Order_Date_Parsed"].dt.year
)

print("\nORDER ID / ORDER DATE YEAR MISMATCHES")
print(check["Order_Year_Mismatch"].value_counts())

# 3. Inspect original date strings
print("\nORIGINAL DATE VALUES")
display(
    check[
        ["Order ID", "Order Date", "Ship Date"]
    ].head(20)
)

# 4. Inspect records with the shortest and longest intervals
print("\n10 SHORTEST LEAD TIMES")
display(
    check.nsmallest(
        10, "Lead_Time_Days"
    )[
        ["Order ID", "Order Date", "Ship Date",
         "Lead_Time_Days"]
    ]
)

print("\n10 LONGEST LEAD TIMES")
display(
    check.nlargest(
        10, "Lead_Time_Days"
    )[
        ["Order ID", "Order Date", "Ship Date",
         "Lead_Time_Days"]
    ]
)

# 5. Check whether the source contains multiple date formats
print("\nRAW ORDER DATE EXAMPLES")
print(check["Order Date"].astype(str).unique()[:15])

print("\nRAW SHIP DATE EXAMPLES")
print(check["Ship Date"].astype(str).unique()[:15])

ORDER ID YEAR COUNTS
Order_ID_Year
2021.0    1993
2022.0    2102
2023.0    2587
2024.0    3312
Name: count, dtype: int64

ORDER DATE YEAR COUNTS
Order_Date_Parsed
2024    4181
2025    6013
Name: count, dtype: int64

SHIP DATE YEAR COUNTS
Ship_Date_Parsed
2026     711
2027    2089
2028    2367
2029    2899
2030    2128
Name: count, dtype: int64

ORDER ID / ORDER DATE YEAR MISMATCHES
Order_Year_Mismatch
True    10194
Name: count, dtype: int64

ORIGINAL DATE VALUES

                        Order ID  Order Date   Ship Date
0   US-2021-103800-CHO-MIL-31000  03-01-2024  30-06-2026
1   US-2021-112326-CHO-TRI-54000  04-01-2024  01-07-2026
2   US-2021-112326-CHO-NUT-13000  04-01-2024  01-07-2026
3   US-2021-112326-CHO-SCR-58000  04-01-2024  01-07-2026
4   US-2021-141817-CHO-TRI-54000  05-01-2024  05-07-2026
5   US-2021-167199-CHO-SCR-58000  06-01-2024  03-07-2026
6   US-2021-167199-CHO-TRI-54000  06-01-2024  03-07-2026
7   US-2021-106054-CHO-MIL-31000  06-01-2024  30-06-2026
8   US-2021-167199-CHO-NUT-13000  06-01-2024  03-07-2026
9   US-2021-167199-CHO-MIL-31000  06-01-2024  03-07-2026
10  US-2021-167199-CHO-MIL-31000  06-01-2024  03-07-2026
11  US-2021-130813-CHO-MIL-31000  06-01-2024  01-07-2026
12  US-2021-167199-CHO-SCR-58000  06-01-2024  03-07-2026
13  US-2021-167199-CHO-FUD-51000  06-01-2024  03-07-2026
14  US-2021-105417-CHO-MIL-31000  07-01-2024  05-07-2026
15  US-2021-105417-CHO-TRI-54000  07-01-2024  05-07-2026
16  US-2021-135405-CHO-TRI-54000  09-01-2024  06-07-2026
17  US-2021-135405-CHO-TRI-54000  09-01-2024  06-07-2026
18  US-2021-149020-CHO-MIL-31000  10-01-2024  08-07-2026
19  US-2021-149020-OTH-GUM-21000  10-01-2024  08-07-2026

10 SHORTEST LEAD TIMES

                         Order ID  Order Date   Ship Date  Lead_Time_Days
154  US-2021-116239-CHO-FUD-51000  04-03-2024  25-08-2026             904
203  US-2021-158442-CHO-MIL-31000  17-03-2024  07-09-2026             904
211  US-2021-158442-CHO-FUD-51000  17-03-2024  07-09-2026             904
212  US-2021-158442-CHO-TRI-54000  17-03-2024  07-09-2026             904
247  US-2021-129609-CHO-TRI-54000  22-03-2024  12-09-2026             904
280  US-2021-130428-CHO-FUD-51000  31-03-2024  21-09-2026             904
282  US-2021-130428-CHO-TRI-54000  31-03-2024  21-09-2026             904
284  US-2021-130428-CHO-FUD-51000  31-03-2024  21-09-2026             904
286  US-2021-112403-CHO-NUT-13000  31-03-2024  21-09-2026             904
338  US-2021-165806-CHO-MIL-31000  07-04-2024  28-09-2026             904

10 LONGEST LEAD TIMES

                          Order ID  Order Date   Ship Date  Lead_Time_Days
7063  US-2024-136007-CHO-SCR-58000  23-02-2025  23-08-2029            1642
7065  US-2024-136007-CHO-TRI-54000  23-02-2025  23-08-2029            1642
7094  US-2024-111815-CHO-SCR-58000  03-03-2025  31-08-2029            1642
7100  US-2024-111815-CHO-TRI-54000  03-03-2025  31-08-2029            1642
7130  US-2024-104080-CHO-NUT-13000  08-03-2025  05-09-2029            1642
7131  US-2024-104080-CHO-TRI-54000  08-03-2025  05-09-2029            1642
7167  US-2024-105851-CHO-NUT-13000  13-03-2025  10-09-2029            1642
7276  US-2024-113208-CHO-TRI-54000  26-03-2025  23-09-2029            1642
7279  US-2024-162033-CHO-TRI-54000  26-03-2025  23-09-2029            1642
7283  US-2024-162033-CHO-MIL-31000  26-03-2025  23-09-2029            1642

RAW ORDER DATE EXAMPLES
['03-01-2024' '04-01-2024' '05-01-2024' '06-01-2024' '07-01-2024'
 '09-01-2024' '10-01-2024' '11-01-2024' '13-01-2024' '14-01-2024'
 '15-01-2024' '16-01-2024' '18-01-2024' '19-01-2024' '20-01-2024']

RAW SHIP DATE EXAMPLES
['30-06-2026' '01-07-2026' '05-07-2026' '03-07-2026' '06-07-2026'
 '08-07-2026' '07-07-2026' '11-07-2026' '09-07-2026' '10-07-2026'
 '14-07-2026' '13-07-2026' '19-07-2026' '18-07-2026' '16-07-2026']

In [10]:

# ============================================================
# STEP 5: DATA QUALITY FINDINGS
# ============================================================

print("DATA QUALITY INVESTIGATION")

print("Total records examined: 10,194")
print("Order dates: 2024–2025")
print("Ship dates: 2026–2030")
print("Median calculated interval: 1,274 days")

print("\nCONCLUSION:")
print(
    "The date fields require verification against the "
    "original data source."
)

print(
    "Lead time will not be used as a prediction target "
    "until its validity is established."
)

print(
    "Next: analyze sales and profitability using "
    "the available financial and product fields."
)

DATA QUALITY INVESTIGATION
Total records examined: 10,194
Order dates: 2024–2025
Ship dates: 2026–2030
Median calculated interval: 1,274 days

CONCLUSION:
The date fields require verification against the original data source.
Lead time will not be used as a prediction target until its validity is established.
Next: analyze sales and profitability using the available financial and product fields.

In [11]:
# Step 5: Date Validation
## Factory Reallocation & Shipping Optimization Recommendation System

### Objective
# Validate order dates and shipping dates.
# Calculate shipping lead time.
# Identify inconsistent or suspicious date values.
# Decide whether lead time is reliable enough for machine learning.

In [12]:
df = pd.read_csv("Nassau Candy Distributor.csv")
print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
df.head()

Dataset loaded successfully!
Dataset shape: (10194, 18)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [13]:
print("Date columns:")
print(df[["Order Date", "Ship Date"]].head(10))
print("\nOriginal data types:")
print(df[["Order Date", "Ship Date"]].dtypes)

Date columns:
   Order Date   Ship Date
0  03-01-2024  30-06-2026
1  04-01-2024  01-07-2026
2  04-01-2024  01-07-2026
3  04-01-2024  01-07-2026
4  05-01-2024  05-07-2026
5  06-01-2024  03-07-2026
6  06-01-2024  03-07-2026
7  06-01-2024  30-06-2026
8  06-01-2024  03-07-2026
9  06-01-2024  03-07-2026

Original data types:
Order Date    object
Ship Date     object
dtype: object

In [14]:
df["Order Date"] = pd.to_datetime(df["Order Date"],format="%d-%m-%Y",errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"],format="%d-%m-%Y",errors="coerce")
df["Lead_Time_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days
print("Date conversion completed.")
df[["Order Date", "Ship Date", "Lead_Time_Days"]].head(10)

Date conversion completed.

  Order Date  Ship Date  Lead_Time_Days
0 2024-01-03 2026-06-30             909
1 2024-01-04 2026-07-01             909
2 2024-01-04 2026-07-01             909
3 2024-01-04 2026-07-01             909
4 2024-01-05 2026-07-05             912
5 2024-01-06 2026-07-03             909
6 2024-01-06 2026-07-03             909
7 2024-01-06 2026-06-30             906
8 2024-01-06 2026-07-03             909
9 2024-01-06 2026-07-03             909

In [15]:
print("Missing or invalid order dates:",df["Order Date"].isna().sum())
print("Missing or invalid ship dates:",df["Ship Date"].isna().sum())
print("Negative lead times:",(df["Lead_Time_Days"] < 0).sum())
print("Lead times over 90 days:",(df["Lead_Time_Days"] > 90).sum())
print("\nLead-time summary:")
print(df["Lead_Time_Days"].describe())

Missing or invalid order dates: 0
Missing or invalid ship dates: 0
Negative lead times: 0
Lead times over 90 days: 10194

Lead-time summary:
count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead_Time_Days, dtype: float64

In [16]:
print("Order Date range:")
print(df["Order Date"].min(), "to", df["Order Date"].max())

print("\nShip Date range:")
print(df["Ship Date"].min(), "to", df["Ship Date"].max())

print("\nOrder Date year counts:")
print(df["Order Date"].dt.year.value_counts().sort_index())

print("\nShip Date year counts:")
print(df["Ship Date"].dt.year.value_counts().sort_index())

Order Date range:
2024-01-02 00:00:00 to 2025-12-31 00:00:00

Ship Date range:
2026-06-30 00:00:00 to 2030-06-28 00:00:00

Order Date year counts:
Order Date
2024    4181
2025    6013
Name: count, dtype: int64

Ship Date year counts:
Ship Date
2026     711
2027    2089
2028    2367
2029    2899
2030    2128
Name: count, dtype: int64

In [17]:
df.to_csv("nassau_date_validation_results.csv", index=False)
print("Validation results saved successfully!")

Validation results saved successfully!